import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Knowledge Tree",
  description: "Learn about a huge amount of subjects, one course at a time.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="border-b border-amber-900/15 bg-parchment/80 backdrop-blur sticky top-0 z-10">
          <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
            <Link href="/" className="text-xl font-semibold tracking-tight">
              Knowledge Tree
            </Link>
            <nav className="flex gap-6 text-sm">
              <Link href="/" className="hover:text-amber-700">Browse</Link>
              <Link href="/certificates" className="hover:text-amber-700">Certificates</Link>
            </nav>
          </div>
        </header>
        <main className="max-w-5xl mx-auto px-6 py-10">{children}</main>
        <footer className="max-w-5xl mx-auto px-6 py-8 text-xs text-ink/50 border-t border-amber-900/10 mt-16">
          Prototype · Courses generated by Claude on demand and cached.
        </footer>
      </body>
    </html>
  );
}
